image: quay.io/govcms/govcms-ci
services:
- docker:dind
stages:
- build
- deploy
build:
  stage: build
  script:
  - export DOCKER_HOST=tcp://localhost:2375
  - docker network prune -f && docker network create amazeeio-network
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry-production.govcms.amazee.io
  - ahoy up
  - docker-compose exec -T test dockerize -wait tcp://mariadb:3306 -timeout 1m
  - |
    if grep --quiet '^MARIADB_DATA_IMAGE' .env; then
      ahoy govcms-deploy
    else
      ahoy -v install
    fi
  - ahoy lint || true
  - ahoy test-phpunit || true
  - ahoy test-behat || true
  - ahoy audit-site || true
  artifacts:
    paths:
    - tests/behat/features/screenshots
    expire_in: 7 days
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /GovCMS-Migration/
deploy:
  stage: deploy
  variables:
    GOVCMS_DASHBOARD: "https://dashboard.govcms.gov.au/projects"
  script:
    - echo "Deployment triggered, please see $GOVCMS_DASHBOARD/$CI_PROJECT_NAME/$CI_PROJECT_NAME-$(echo $CI_COMMIT_REF_NAME | sed -e 's/[^[:alnum:]-]/-/g')"
