FROM govcmslagoon/govcms7

RUN rm -rf /app
COPY . /app
COPY .docker/scripts/govcms-deploy /usr/bin/
COPY .docker/scripts/aliases.drushrc.php /home/.drush/site-aliases/

# Define where the Drupal Root is located
ENV WEBROOT=docroot
